abstract class AppStrings {
  Map<String, String> get keys;
}

class AppStringsEn extends AppStrings {
  @override
  Map<String, String> get keys => {
    'imageLogo': 'assets/Logo.png',
    'avaRewaseIcon': 'assets/ava_rewase.png',
    'editIcon': 'assets/edit.png',
    'cancelIcon': 'assets/cancel.png',
    'accountIcon': 'assets/account.png',
    'translateIcon': 'assets/translate.png',
    'settingsIcon': 'assets/settings.png',
    'fAQIcon': 'assets/faq.png',
    'copyRight': 'Take-out service program Mosa Al-Nabi family for technological and information services The Churches of the Virgin Mary and Bishop Bishoy The Virgin Mary and Bishop Royce At the Cathedral of Bishop Royce in Abbasiya Version 1.0 Copyright 2024',
    'loginTitle': 'AVA REWASE VISIT',
    'passwordTitle': 'Password',
    'passwordValidate1': 'Please enter your password',
    'passwordValidate2': 'Password must be at least 6 characters',
    'userTitle': 'E1C1FXXXXNRX',
    'userValidate': 'Please enter your ARID!',
    'login': 'Login',
    'loginLoading': 'Login',
    'visitTitle': 'Visit list',
    'visitDetailsTitle': 'Visit Details',
    'yesterday': 'Yesterday',
    'today': 'Today',
    'tomorrow': 'Tomorrow',
    'noOfPeople': 'No. of people',
    'father': 'Father',
    'servant': 'Servant',
    'zone': 'Zone',
    'newVisitTitle': 'New Visit',
    'editVisitTitle': 'Edit Visit',
    'submit': 'Submit',
    'edit': 'Edit',
    'cancel': 'Cancel',
    'clone': 'Copy',
    'arid': 'ARID',
    'patientName': 'Patient Name',
    'assistantName': 'Assistant Name',
    'patientNameValidate': 'Patient name can\'t be empty',
    'assistantNameValidate': 'assistant name must be entered',
    'assistantPhoneNumberValidate1': 'assistant phone must be entered',
    'assistantPhoneNumberValidate2': 'Phone must consist of 11 numbers',
    'patientPhoneNumber': 'Patient Phone',
    'assistantPhoneNumber': 'Assistant Phone',
    'addressType': 'Address Type',
    'address': 'Address',
    'date': 'Date',
    'time': 'Time',
    'from': 'From:',
    'english': 'English',
    'start': 'Start',
    'end': 'End',
    'fromValidate': 'Start time of visit must be chosen',
    'to': 'To:',
    'yes': 'Yes',
    'no': 'No',
    'notes': 'Notes',
    'assign': 'Assign',
    'done': 'Done',
    'profile': 'Profile',
    'account': 'Account',
    'fAQ': 'FAQ',
    'settings': 'Settings',
    'language': 'Language',
    'languageComfim': 'choose your language',
    'toValidate': 'End time of visit must be chosen',
    'dateValidate': 'Date of visit must be chosen',
    'googleMapsLink': 'Location',
    'addressValidate': 'Patient\'s address must be entered',
    'cancelComfirm': 'You want to Cancel this Visit?',
    'cloneComfirm': 'You want to Clone this Visit?',
    'editComfirm': 'You sure to submit edit?',
    'newComfirm': 'You sure to submit new visit?',
    'assignComfirm': 'Choose who You want to assign to?',
    'doneComfirm': 'This Visit is Done?',
    'lang': 'English',
    'arabic': 'Arabic',
    'logout': 'Logout',
    'assignPerson': 'You want to Assign',
    'noVisits': 'No Visits',
    'user': 'patient name',
    'me': 'Me',
    'All': 'All',
    'search':'Search'
  };
}

class AppStringsAr extends AppStrings {
  @override
  Map<String, String> get keys => {
    'imageLogo': 'assets/Logo.png',
    'avaRewaseIcon': 'assets/ava_rewase.png',
    'editIcon': 'assets/edit.png',
    'cancelIcon': 'assets/cancel.png',
    'accountIcon': 'assets/account.png',
    'translateIcon': 'assets/translate.png',
    'settingsIcon': 'assets/settings.png',
    'fAQIcon': 'assets/faq.png',
    'copyRight': 'برنامج خدمة التناول الخارجي أسرة موسى النبي للخدمات التكنولوجية والمعلوماتية كنيستا السيدة العذراء والأنبا بيشوي والسيدة العذراء والأنبا رويس بالكاتدرائية بالأنبا رويس بالعباسية إصدار ١.٠ Copyright 2024',
    'loginTitle': 'برنامج خدمة التناول الخارجي',
    'passwordTitle': 'ادخل كلمة السر',
    'passwordValidate1': 'رجاء ادخال كلمه السر',
    'passwordValidate2': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
    'userTitle': 'ادخل رقم العضويه',
    'arid': 'رقم العضويه',
    'userValidate': 'رجاء ادخال رقم العضوية',
    'login': 'تسجيل الدخول',
    'loginLoading': 'تسجيل الدخول...',
    'visitTitle': 'قائمة الزيارة',
    'visitDetailsTitle': 'تفاصيل الزيارة',
    'yesterday': 'امس',
    'today': 'اليوم',
    'tomorrow': 'غدا',
    'noOfPeople': 'عدد الاشخاص',
    'father': 'الكاهن',
    'servant': 'الخادم',
    'zone': 'المنطقة',
    'newVisitTitle': 'زيارة جديدة',
    'editVisitTitle': 'تعديل زيارة',
    'submit': 'اضف',
    'edit': 'تعديل',
    'cancel': 'الغاء',
    'patientName': 'اسم المريض',
    'assistantName': 'اسم المرافق',
    'patientNameValidate': 'لا يمكن أن يكون اسم المريض فارغًا',
    'assistantNameValidate': 'لا يمكن أن يكون اسم المرافق فارغًا',
    'patientPhoneNumber': 'رقم هاتف المريض',
    'assistantPhoneNumber': 'رقم هاتف المرافق',
    'assistantPhoneNumberValidate1': 'لا يمكن أن يكون هاتف المرافق فارغًا',
    'assistantPhoneNumberValidate2': 'يجب أن يتكون الهاتف من 11 رقم',
    'addressType': 'نوع العنوان',
    'address': 'العنوان',
    'profile': 'الملف الشخصي',
    'date': 'تاريخ الزيارة',
    'time': 'وقت الزيارة',
    'from': 'من:',
    'start': 'يبدا',
    'end': 'ينتهي',
    'fromValidate ': 'يجب اختيار وقت بدء الزيارة',
    'to': 'الي:',
    'yes': 'نعم',
    'no': 'لا',
    'clone': 'نسخ',
    'toValidate': 'يجب اختيار وقت انتهاء الزيارة',
    'dateValidate': 'لا يمكن أن يكون تاريخ الزيارة فارغًا',
    'googleMapsLink': 'رابط عنوان المريض',
    'addressValidate': 'لا يمكن أن يكون عنوان المريض فارغًا',
    'notes': 'ملحوظات',
    'assign': 'تعيين',
    'done': 'انتهت',
    'cancelComfirm': 'هل تريد إلغاء هذه الزيارة؟',
    'cloneComfirm': 'هل تريد نسخ هذه الزيارة؟',
    'editComfirm': 'هل أنت متأكد من تقديم التعديل؟',
    'newComfirm': 'هل أنت متأكد من تقديم زيارة جديدة؟',
    'assignComfirm': 'اختر من تريد التعيين إليه؟',
    'assignPerson': 'هل تريد التعيين ',
    'doneComfirm': 'هل تمت هذه الزيارة؟',
    'account': 'حسابي',
    'fAQ': 'الاسئلة الشائعة',
    'settings': 'إعدادات',
    'language': 'اللغة',
    'languageComfim': 'اختر لغتك',
    'lang': 'العربيه',
    'english': 'إنجليزي',
    'arabic': 'عربي',
    'logout': 'تسجيل الخروج',
    'noVisits': 'لا توجد زيارات',
    'user': 'اسم المريض',
    'me': 'انا',
    'All': 'الكل',
    'search':'بحث'
  };
}
