// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_iC5eEbsPKmC0FJx4OCtM6560FuUBH0U',
    appId: '1:591391910151:web:42278a0a267a54d831fda2',
    messagingSenderId: '591391910151',
    projectId: 'visits-project-75568',
    authDomain: 'visits-project-75568.firebaseapp.com',
    storageBucket: 'visits-project-75568.appspot.com',
    measurementId: 'G-9D0ZGZ3G0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JnaTwwV5Ck6JQzLsADkYUyIQ20BixBc',
    appId: '1:591391910151:android:940813d3de0d9b0731fda2',
    messagingSenderId: '591391910151',
    projectId: 'visits-project-75568',
    storageBucket: 'visits-project-75568.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyFdZm02aFldPdHuoNvWWtRghwOXd6QOM',
    appId: '1:591391910151:ios:b52a706a0326d8d131fda2',
    messagingSenderId: '591391910151',
    projectId: 'visits-project-75568',
    storageBucket: 'visits-project-75568.appspot.com',
    iosClientId: '591391910151-o3811qo48a1dih4cb85unef80uq9c1e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.arVisitingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_iC5eEbsPKmC0FJx4OCtM6560FuUBH0U',
    appId: '1:591391910151:web:67449c6500df52ae31fda2',
    messagingSenderId: '591391910151',
    projectId: 'visits-project-75568',
    authDomain: 'visits-project-75568.firebaseapp.com',
    storageBucket: 'visits-project-75568.appspot.com',
    measurementId: 'G-QLX8GPJDCR',
  );
}
